Home/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path('', views.dashboard, name='dashboard'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('notification/', views.Notifications.as_view(), name='notification'),
    path(
        'update/profile/<int:pk>/', views.UpdateProfileView.as_view(),
        name='update_profile'
    ),
    path('Settings', views.Setting, name='Settings'),
    path('setting_security', views.setting_security, name='setting_security'),
    path('contact_us', views.contact_us, name='contact_us'),

    # ajax
    path('ajax/read/notification', views.read_notification, name='read_notification'),
]

authentication/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from . import views


urlpatterns=[
    path('sign/up/', views.sign_up, name='sign_up'),
    path('login/', views.Login, name='Login'),
    path('Logout',views.Logout,name='Logout'),
    path('',views.HomeView.as_view(), name='home_view'),
    path('otp/verified', views.otp_verified , name="otp_verified"),
    path('forget_password', views.forget_password , name="forget_password"),
    path('reset_password', views.reset_password , name="reset_password"),
    path('update_password', views.update_password , name="update_password"),
]

googleSearchScraper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from googleSearchApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('google_search/', include('googleSearchApp.urls')),
    path('captcha/', include('captcha.urls')),
    path('dashboard/', include('Home.urls')),
    path('', include('authentication.urls')),
    path('get_emails/', include('Get_Emails_from_Domain.urls')),
    # path('social-auth/', include('social_django.urls', namespace='social')),  # <-- here
    path("", include("allauth.urls")),
    path('social/signup/', views.signup_redirect, name='signup_redirect'),

    path('plans/', include('payment_methods.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models


GENDER = (
    ('1', "Mail"),
    ('2', "Femail"),
)


class Profile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=25, blank=True, null=True, verbose_name='Phone No')
    picture = models.ImageField(upload_to='ProfileImages', blank=True, verbose_name='Photo')
    gender = models.CharField(
        choices=GENDER, max_length=25, blank=True, null=True,
        verbose_name='Gender'
    )
    profession = models.CharField(max_length=25, blank=True, null=True)
    otp = models.CharField(max_length=25, blank=True, null=True, verbose_name='OTP')
    changed_default_password = models.CharField(max_length=500, blank=True, default='No', null=True,verbose_name='Changed Default Password?')
    joined_via = models.CharField(max_length=2500, blank=True, null=True,verbose_name='How joined?')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='Created At')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='Updated At')
    is_lifetime = models.BooleanField(default=False)


    class Meta:
        verbose_name = 'User Profile'

    def __str__(self):
        return self.owner.username


class CommonField(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)

    class Meta:
        abstract = True

class Section(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Landing(CommonField):
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True)
    link = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.section.name


class Price(models.Model):
    models.ForeignKey(Landing, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=100)
    price = models.FloatField(null=True, blank=True, default=0.00)

    def __str__(self):
        return self.title

class Features(models.Model):
    to = models.ForeignKey(Price, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

authentication/views.py
import random

from django.contrib import messages, auth
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from googleSearchScraper.settings import EMAIL_HOST_USER
from payment_methods.models import Price_plan
from .models import Landing, Price
from .models import Profile


class HomeView(View):
    template_name = 'landing.html'
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.profile.changed_default_password == 'No':
            return redirect('dashboard')
        pricing = Price_plan.objects.all()
        banner = Landing.objects.filter(section__code='bn').last()
        intro = Landing.objects.filter(section__code='int')
        pric = Landing.objects.filter(section__code='pric').last()
        last = Landing.objects.filter(section__code='last').last()
        all_price = Price.objects.all()
        context = {
            'banner': banner, 'intro': intro, 'pric': pric,
            'all_price': all_price, 'last': last, 'pricing': pricing
        }
        return render(request, self.template_name, context)


def send_email_otp(x,user_email,otp):

    subject = 'Verification Code'
    html_content = render_to_string(
        'otp_email_template.html',
            {
                'first_name': x.owner.first_name,
                'last_name': x.owner.last_name,'otp':otp
            }
        )
    text_content = strip_tags(html_content)

    msg = EmailMultiAlternatives(subject, text_content, EMAIL_HOST_USER, user_email)
    msg.attach_alternative(html_content, "text/html")
    msg.send()
    return None


def Login(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        if not email:
            messages.error(request, 'Email is required')
            return redirect('Login')
        if not password:
            messages.error(request, 'Password is required')
            return redirect('Login')
        user = auth.authenticate(email=email, password=password)
        if user == None:
            user = auth.authenticate(username=email, password=password)
        if user is not None:

            login(request, user)
            return redirect('dashboard')

        else:
            messages.error(request,'Invalid ID or password')
            return redirect('Login')
    return render(request, 'Login.html')


def sign_up(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        re_password = request.POST.get('re-password')
        if not email:
            messages.error(request, 'Email is required')
            return redirect('sign_up')
        if not password:
            messages.error(request, 'Password is required')
            return redirect('sign_up')
        if not re_password:
            messages.error(request, 'Confirm Password is required')
            return redirect('sign_up')
        if password == re_password:
            user = User.objects.create_user(
                username=email, email=email, password=password, is_active=False
            )
            profile = Profile.objects.create(
                owner=user, changed_default_password='No', joined_via='Manual'
            )
            otp = str(random.randint(1000, 9999))
            profile.otp = otp
            profile.save()
            user_email = []
            user_email.append(user.email)
            send_email_otp(profile, user_email, otp)
            request.session['user_email'] = user.email
            return redirect('otp_verified')
        else:
            messages.error(request,'Not authorized')
            return render(request, 'sign_up.html')
    return render(request, 'sign_up.html')



def Logout(request):
    logout(request)
    messages.info(request,'You have been Logged Out')
    return redirect('Login')


def forget_password(request):
    if request.method == 'POST':
        Username = request.POST.get('un')
        if not Username:
            messages.error(request, 'Email is required')
            return redirect('forget_password')

        user=User.objects.filter(email=Username).first()
        x= Profile.objects.filter(owner=user).first()
        if user is None:
            messages.error(request,'User not found with this Email')
            return render(request, 'forget-password.html')

        otp = str(random.randint(1000, 9999))
        x.otp = otp
        x.save()
        mobile=x.phone
        print(otp)

        user_email = []
        user_email.append(user.email)
        send_email_otp(x, user_email, otp)

        request.session['mobile'] = mobile
        request.session['Username'] = user.email

        return redirect('reset_password')

    return render(request,'forget-password.html')


def otp_verified(request):
    user_email = request.session['user_email']
    if request.method == 'POST':
        otp = request.POST.get('2facode')
        profile = Profile.objects.filter(owner__email=user_email).first()
        if otp == profile.otp:
            user = User.objects.get(email=user_email)
            print(user.is_active, "*" * 100, "Before")
            user.is_active = True
            user.save()
            print(user.is_active, "*" * 100, "After")
            messages.success(request, 'Verification code match successfully')

            return redirect('Login')
        else:
            messages.error(request,'Invalid OTP,please try again')
            return render(request, 'reset_password_otp.html')

    return render(request, 'reset_password_otp.html')


def reset_password(request):
    mobile = request.session['mobile']
    Username = request.session['Username']


    if request.method == 'POST':
        otp = request.POST.get('2facode')
        profile = Profile.objects.filter(owner__email=Username).first()
        if otp == profile.otp:
             request.session['Username'] = Username
             messages.success(request, 'Verification code match successfully')
             return redirect('update_password')
        else:
            messages.error(request,'Invalid OTP,please try again')
            return render(request, 'reset_password_otp.html')

    return render(request, 'reset_password_otp.html')


def update_password(request):
    Username = request.session['Username']


    if request.method == 'POST':
        users = User.objects.get(email=Username)
        user_profile = Profile.objects.get(owner=users)

        new_password = request.POST.get('new_password')



        if len(new_password)!=0:
            users.set_password(new_password)
            user_profile.changed_default_password = 'Yes'
            user_profile.save()
            users.save()

            messages.info(request, 'Password updated successfully,Please Login with New Set Password')
            return redirect('Login')

    else:

     return render(request,'update_password.html')




authentication/templates/Login.html
{% extends 'base.html' %}
{% load static socialaccount  %}
{% block title %}
    Login
{% endblock %}
{% block content %}


<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="#" class="h1"><img src="{% static 'dist/img/traders_brid.PNG' %}" width="60%" height="60%"  alt="" /></a></a>

    </div>
    <div class="card-body">
      <p class="login-box-msg">Sign in to start your session</p>
        <h6>{% include '_messages.html' %}</h6>

      <form action="{% url 'Login' %}" method="post">
            {% csrf_token %}
        <div class="input-group mb-3">
          <input type="email" class="form-control" name="username" placeholder="Email" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" name="password" placeholder="Password" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">

          <!-- /.col -->
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>

          <!-- /.col -->
        </div>
      </form>
  <div class="social-auth-links text-center mb-3">
    <a href="{% provider_login_url 'google'%}?next=/" class="btn btn-block btn-danger">
      <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
    </a>
      </div>

      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="{% url 'forget_password' %}">I forgot my password</a>
      </p>

    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->


</body>

{% endblock %}

authentication/templates/Login_otp.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login OTP
{% endblock %}
{% block content %}


<!-- /.login-box -->


<body class="hold-transition login-page">
<div class="login-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="#" class="h1"><img src="{% static 'dist/img/traders_brid.PNG' %}" width="60%" height="60%" alt="" /></a>
    <h5>Please  open your <b>Google Authenticator app </b> linked with this account and enter the current running OTP here.</h5>
    </div>

    <div class="card-body">
      <p class="login-box-msg">OTP Verification</p>
          <h5 style="text-decoration:#00a65a">{% include '_messages.html' %}</h5>
        <form action="{% url 'login_otp' %}" method="post">
            {% csrf_token %}
        <div class="input-group mb-3">
          <input class="form-control" type="number" name="2facode" min="0"  pattern="/^-?\d+\.?\d*$/" onKeyPress="if(this.value.length==6) return false;" placeholder="Enter Code" required >
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-code"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Login</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

    </div>
    <!-- /.login-card-body -->
  </div>
</div>
</body>



{% endblock %}

authentication/templates/_messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div
        {% if message.tags %} class="alert {{ message.tags }}" {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

authentication/templates/drop_down_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://unpkg.com/bootstrap@3.3.2/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://unpkg.com/jquery@3.3.1/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/bootstrap@3.3.2/dist/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/bootstrap-multiselect@0.9.13/dist/js/bootstrap-multiselect.js"></script>
    <link href="https://unpkg.com/bootstrap-multiselect@0.9.13/dist/css/bootstrap-multiselect.css" rel="stylesheet"/>

</head>
<style>.multiselect-container > li > a > label {
    padding: 4px 20px 3px 20px;
}


select {
    display: block;
    margin: 30% auto;
    font-size: 20px;
}</style>
<body>
<form id="form1">
    <div style="padding:20px">

{#        <select id="chkveg" multiple="multiple">#}
{##}
{#            <option value="">project.xml</option>#}
{#            <optgroup label="client1">#}
{#                <option value="">project2.xml</option>#}
{#            </optgroup>#}
{#            <optgroup label="client2">#}
{#                <option value="">project5.xml</option>#}
{#                <option value="">project6.xml</option>#}
{#                <optgroup label="client2_a">#}
{#                    <option value="" style="margin-left:23px;">project7.xml</option>#}
{#                    <option value="" style="margin-left:23px;">project8.xml</option>#}
{#                </optgroup>#}
{#                <option value="">project3.xml</option>#}
{#                <option value="">project4.xml</option>#}
{#            </optgroup>#}
{#            <option value="">project0.xml</option>#}
{#            <option value="">project1.xml</option>#}

{#        <ul  class="dropdown" style="display: none">#}
{#            <li> <input type="checkbox" class="dropdown-toggle"> Pakistan  <ul>#}
{#                <li><input type="checkbox">KPK</li>#}
{#                 <li><input type="checkbox">Punjab#}
{#                     <ul >#}
{#                         <li><input type="checkbox">Lahore</li>#}
{#                         <li><input type="checkbox">Chakwal</li>#}
{#                     </ul>#}
{#                 </li>#}
{#                 <li><input type="checkbox">Sindh</li>#}
{#                <li><input type="checkbox">Balochistan</li>#}
{#            </ul>#}
{#            </li>#}
{##}
{#            <li> Pakistan  <ul>#}
{#                <li>KPK</li>#}
{#                <li>Punjab</li>#}
{#                <li>Sindh</li>#}
{#                <li>Balochistan</li>#}
{#            </ul>#}
{#            </li>#}
{#        </ul>#}
{#        </select>#}
        <li data-id="1">
    <input class="cat_check" data-pid="0" type="checkbox" value="1" id="1" checked/>Exterior Signs
        <ul class="category_select_list">
            <li data-id="15">
                <input class="cat_check" data-pid="1" type="checkbox" value="15" id="15" checked/>Monument
            </li>
            <li data-id="17">
                <input class="cat_check" data-pid="1" type="checkbox" value="17" id="17" checked/>Channel Letters
                <ul class="category_select_list">
                    <li data-id="28">
                        <input class="cat_check" data-pid="17" type="checkbox" value="28" id="28" checked/>Neon Channel Letter
                    </li>
                </ul>
            </li>
            <li data-id="16">
                <input class="cat_check" data-pid="1" type="checkbox" value="16" id="16" checked/>Banners
            </li>
        </ul>
    </li>

        <br/><br/>

        <input type="button" id="btnget" value="Get Selected Values"/>
    </div>
</form>


</body>
<script>
 function checkSiblings(target) {
    var siblingsChecked = 0;
    target.parent('li').siblings('li').children('input').each(function(i, el){
        if ($(el).is(':checked')) {
            siblingsChecked++;
        }
    });

    if (siblingsChecked === 0) {
        var possibleParent = target.parent('li').parents('li').eq(0).children('input');
        if (possibleParent.length) {
            //console.log('we have a parent');
            possibleParent.prop('checked', false);
        }
        else {
            //console.log('nothing');
        }
    }
}

$('.cat_check').on('click', function (ev) {
    if ($(this).is(':checked')) {
        // check all children
        $(this).parent('li').each(function(i, el){
            $(el).find('input').prop('checked', true);
        });
        // check inputs on the way up
        $(this).parents('li').each(function(i, el){
            $(el).children('input').prop('checked', true);
        });
    }
    else {
        $(this).parent('li').find('input').prop('checked', false);
        checkSiblings($(this));
    }
});
</script>
</html>

authentication/templates/forget-password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Forgot Password
{% endblock %}
{% block content %}






    <body class="hold-transition login-page">
<div class="login-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="#" class="h1"><img src="{% static 'dist/img/traders_brid.PNG' %}" width="60%" height="60%"  alt="" /></a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>
          <h5 style="text-decoration:#00a65a">{% include '_messages.html' %}</h5>
        <form action="{% url 'forget_password' %}" method="post">
            {% csrf_token %}
        <div class="input-group mb-3">
          <input type="email" class="form-control"  name="un" placeholder="Enter Email" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <p class="mt-3 mb-1">
        <a href="{% url 'Login' %}">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
    </body>
{% endblock %}

authentication/templates/landing.html
<!DOCTYPE html>
<html lang="fr-FR">
{% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <link href="{% static 'dist/img/Sans titre (39).png' %}" rel="icon">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <style>
        .btn{
            width: 125px !important;
        }
        @media(max-width:575.98px) {
            .col {
                flex-basis: auto !important;
            }
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Login' %}">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <b>Log In</b>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary text-light" href="{% url 'sign_up' %}">
                            <b>Get Start</b>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section id="banner" class="my-5 py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 text-center m-auto">
                    <h1>{{ banner.title }}</h1>
                    <p class="p-4">{{ banner.subtitle }}</p>
                    <!-- <iframe width="600" height="330" src="https://www.youtube.com/embed/{{ banner.link }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> -->
                    <!-- <img class="w-100" src="{% static 'img/banner.gif' %}" alt="">
                    <br><br> -->
                    <video width="100%" controls loop autoplay muted controlsList="nodownload">
                        <source src="{% static 'video/video.mp4' %}" type="video/mp4">
                    </video>
                    <br>
                    <br>
                    <br>
                    <a class="btn btn-primary text-light" href="{% url 'sign_up' %}">
                        <b>Get Start</b>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section id="intro" class="my-5 py-5">
        <div class="container">
            <div class="row">
                {% for obj in intro %}
                <div class="col-md-3 text-center m-auto">
                    <div class="intro-section">
                        <img src="{% static 'img/img.png' %}" alt="">
                        <h2><b>{{ obj.title }}</b></h2>
                        <p>{{ obj.subtitle }}</p>
                    </div>
                </div>
                <div class="com-md-1"></div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section id="pricing" class="my-5 py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{{ pric.title }}</h1>
                    <p>{{ pric.subtitle }} {{ pric.features_set }}</p>
                </div>
            </div>
        </div>
    </section>
    <section id="pricing" class="my-5 py-5">
        <div class="container">
            <div class="row">
                <div class="col my-4">
                    <div class="card">
                        <div class="card-header text-center">
                            <h5>Pay as Go</h5>
                        </div>
                      <div class="card-body pt-0">
                        <div class="row">
                              <div class="col-12 text-center" style="padding: 20px 0 30px 0;">
                                <p><b>You have to pay <b> $0.01 per line</b> depending upon <b>No of queries </b></b></p>
                                <p><b>0.01 $ / lines</b></p>
                                   <p><b>Expensive for regular customers</b></p>
                                   <p><b>Buy any plan to save your cost</b></p>
                              </div>
                        </div>
                      </div>
                      <div class="card-footer">
                        <div class="text-center">
                          <a href="{% url 'dashboard' %}" class="btn btn-md btn-info">
                            <i class="fas fa-sign-in-alt"></i> Pay as Go
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% for plan in pricing %}
                <div class="col my-4">
                    <div class="card">
                        <div class="card-header text-center">
                            <h5>{{plan.title}}</h5>
                        </div>
                    <div class="card-body pt-0">
                        <div class="row">
                            <div class="col-12 text-center mt-2">
                            <img src="{{plan.plan_img.url}}" alt="user-avatar" class="img-circle img-fluid">
                            </div>
                            <br>
                            <div class="col-12 text-center">
                                <p><b>Price: ${{plan.price}}</b></p>
                                <p><b>{{plan.no_of_lines}} lines per month</b></p>
                                <p><b>{{ plan.perline_price }} $ / lines</b></p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                        <a href="{% url 'checkout' plan.id %}" class="btn btn-md btn-info">
                            Subscribe Now
                        </a>
                        </div>
                    </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section id="start" class="my-5 py-5">
        <div class="container">
            <div class="col-md-8 text-center m-auto">
                <h3><b>{{ last.title }}</b></h3>
                <p>{{ last.subtitle }}</p>
                <a href="{% url 'Login' %}" class="btn btn-outline-primary">Login</a>
                <a href="{% url 'sign_up' %}" class="btn btn btn-primary">Get Start</a>
            </div>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
</body>

</html>